FROM node:latest
RUN apt-get update && apt-get install -y wget gnupg && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install -y google-chrome-stable

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install selenium-webdriver
COPY . .
EXPOSE 8080
CMD ["node", "index"]
